from typing import Protocol

from app.domain.commands import RobotCommand
from app.domain.state import RobotState


class RobotAdapter(Protocol):
    async def connect(self) -> None: ...
    async def execute(self, command: RobotCommand) -> None: ...
    async def stop(self) -> None: ...
    async def reset(self) -> None: ...
    async def get_state(self) -> RobotState: ...
